# Generated by Django 6.0.2 on 2026-07-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='free_reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
