# Generated by Django 5.2.1 on 2026-07-25 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_free_reschedule'),
        ('doctors', '0005_doctor_days'),
        ('hospitals', '0007_hospital_latitude_hospital_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='queue_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='queue_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('queue_payment_id', ''), _negated=True), fields=('queue_payment_id',), name='uniq_booking_queue_payment_id_nonblank'),
        ),
    ]
