# Generated by Django 5.2.1 on 2026-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_queue_order_id_booking_queue_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_for_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_for_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
