# Generated by Django 5.2.1 on 2026-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_rename_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor_payout_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='PENDING', max_length=12),
        ),
    ]
