# Generated by Django 6.0.2 on 2026-08-18 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_doctor_payout_status'),
        ('doctors', '0013_doctor_view_count'),
        ('hospitals', '0012_hospital_kind'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scans.scan'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='doctors.doctor'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scan', 'date', 'status'], name='idx_booking_scan_date_status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('doctor__isnull', False), ('scan__isnull', True)), models.Q(('doctor__isnull', True), ('scan__isnull', False)), _connector='OR'), name='booking_exactly_one_provider'),
        ),
    ]
