# Generated by Django 5.2.1 on 2026-09-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_scan_alter_booking_doctor_and_more'),
        ('payments', '0012_appointmentpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.appointmentpass'),
        ),
    ]
