# Generated by Django 5.2.1 on 2026-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_booking_appointment_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="called_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
