# Generated by Django 6.0.2 on 2026-06-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsapplog',
            new_name='notificatio_booking_142598_idx',
            old_name='notif_booking_event_idx',
        ),
    ]
