# Generated by Django 5.2.1 on 2026-07-20 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='expo_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='devicetoken',
            constraint=models.UniqueConstraint(fields=('expo_token', 'role'), name='uniq_device_token_per_role'),
        ),
    ]
