# Generated by Django 6.0.2 on 2026-07-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_devicetoken_expo_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable')], max_length=30),
        ),
    ]
