# Generated by Django 5.2.1 on 2026-07-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_whatsapplog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable'), ('hospital_new_booking', 'Hospital New Booking')], max_length=30),
        ),
    ]
