# Generated by Django 5.2.1 on 2026-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_whatsapplog_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable'), ('hospital_new_booking', 'Hospital New Booking'), ('doctor_payout', 'Doctor Payout Paid'), ('booking_cancelled', 'Booking Cancelled'), ('booking_no_show', 'Booking No-show')], max_length=30),
        ),
    ]
