# Generated by Django 6.0.2 on 2026-08-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds three event_type choices for the new WhatsApp senders.

    Choices are Python-level metadata: max_length stays 30 and the column is
    untouched, so this is safe to run before the code that writes the new values
    (Railway migrates and deploys as separate steps) and safe against the
    existing log rows, which keep their current event_type.
    """

    dependencies = [
        ('notifications', '0008_alter_whatsapplog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable'), ('hospital_new_booking', 'Hospital New Booking'), ('doctor_payout', 'Doctor Payout Paid'), ('booking_cancelled', 'Booking Cancelled'), ('booking_no_show', 'Booking No-show'), ('queue_advance', 'Queue Advance (you are next)'), ('booking_on_hold', 'Booking On Hold'), ('hospital_cancellation', 'Hospital Cancellation Alert')], max_length=30),
        ),
    ]
