# Generated by Django 6.0.2 on 2026-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    """Lists four event_type values the senders already write.

    Choices are Python-level metadata: max_length stays 30 and the column is
    untouched, so this runs no SQL against the live log table and is safe
    before the code that writes the values (Railway migrates and deploys as
    separate steps). Same shape as 0005/0006/0008/0009.

    Named off the default `0010_alter_whatsapplog_event_type` because the
    unmerged pass-expiry branch adds a 0010 to this app too; whichever merges
    second still has to re-parent its dependency, but not fight over a file.
    """

    dependencies = [
        ('notifications', '0009_alter_whatsapplog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable'), ('hospital_new_booking', 'Hospital New Booking'), ('doctor_payout', 'Doctor Payout Paid'), ('booking_cancelled', 'Booking Cancelled'), ('booking_no_show', 'Booking No-show'), ('queue_advance', 'Queue Advance (you are next)'), ('booking_on_hold', 'Booking On Hold'), ('hospital_cancellation', 'Hospital Cancellation Alert'), ('scan_report_ready', 'Scan Report Ready'), ('centre_new_booking', 'Centre New Booking'), ('centre_payout', 'Centre Payout Paid'), ('appointment_prep', 'Appointment Preparation')], max_length=30),
        ),
    ]
