# Generated by Django 6.0.2 on 2026-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the `pass_expiring` event_type choice for the expiry nudge.

    Choices are Python-level metadata: max_length stays 30 and the column is
    untouched, so this runs no SQL against the live log table and is safe to
    run before the code that writes the value (Railway migrates and deploys as
    separate steps). Same shape as 0005/0006/0008/0009/0010.
    """

    dependencies = [
        ('notifications', '0010_whatsapplog_scan_and_centre_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable'), ('hospital_new_booking', 'Hospital New Booking'), ('doctor_payout', 'Doctor Payout Paid'), ('booking_cancelled', 'Booking Cancelled'), ('booking_no_show', 'Booking No-show'), ('queue_advance', 'Queue Advance (you are next)'), ('booking_on_hold', 'Booking On Hold'), ('hospital_cancellation', 'Hospital Cancellation Alert'), ('scan_report_ready', 'Scan Report Ready'), ('centre_new_booking', 'Centre New Booking'), ('centre_payout', 'Centre Payout Paid'), ('appointment_prep', 'Appointment Preparation'), ('pass_expiring', 'Appointment Pass Expiring')], max_length=30),
        ),
    ]
