# Generated by Django 6.0.2 on 2026-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_whatsapplog_pass_expiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('doctor_unavailable', 'Doctor Unavailable'), ('hospital_new_booking', 'Hospital New Booking'), ('doctor_payout', 'Doctor Payout Paid'), ('booking_cancelled', 'Booking Cancelled'), ('booking_no_show', 'Booking No-show'), ('queue_advance', 'Queue Advance (you are next)'), ('booking_on_hold', 'Booking On Hold'), ('hospital_cancellation', 'Hospital Cancellation Alert'), ('scan_report_ready', 'Scan Report Ready'), ('centre_new_booking', 'Centre New Booking'), ('centre_payout', 'Centre Payout Paid'), ('appointment_prep', 'Appointment Preparation'), ('pass_expiring', 'Appointment Pass Expiring'), ('doctor_delay', 'Doctor Running Late')], max_length=30),
        ),
    ]
