# Generated by Django 6.0.2 on 2026-08-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0012_hospital_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modality', models.CharField(blank=True, default='', max_length=100)),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('prep_instructions', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('available', models.BooleanField(default=True)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('days', models.JSONField(blank=True, default=list)),
                ('max_per_slot', models.IntegerField(default=1)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('payment_collection_mode', models.CharField(choices=[('FULL', 'Scan Price + Service Fee'), ('SERVICE_ONLY', 'Service Fee Only')], default='SERVICE_ONLY', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['center', 'available'], name='idx_scan_center_available')],
            },
        ),
    ]
