# Generated by Django 5.2.1 on 2026-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scanreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
