# Generated by Django 5.2.1 on 2026-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scanreport_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='booking_cutoff_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
