# Generated by Django 5.2.1 on 2026-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
