# Generated by Django 5.2.1 on 2026-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_hospital_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ifsc',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='hospital',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK', 'Bank Account')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='payout_notes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='hospital',
            name='upi_vpa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
