# Generated by Django 5.2.1 on 2026-08-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_hospital_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='commission_rate',
        ),
    ]
