# Generated by Django 5.2.1 on 2026-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_remove_hospital_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='announcement_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='landline',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
