# Generated by Django 6.0.2 on 2026-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_hospital_announcement_until_hospital_landline'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='kind',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital / Clinic'), ('SCAN_CENTER', 'Scanning Centre')], db_index=True, default='HOSPITAL', max_length=20),
        ),
    ]
