# Generated by Django 5.2.1 on 2026-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_hospital_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
