# Generated by Django 5.2.1 on 2026-08-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0013_hospital_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='kind',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital / Clinic'), ('SCAN_CENTER', 'Scanning Centre'), ('BLOOD_CENTER', 'Blood Centre / Pathology Lab')], db_index=True, default='HOSPITAL', max_length=20),
        ),
    ]
