# Generated by Django 5.2.1 on 2026-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0014_alter_hospital_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='svc_blood',
            field=models.CharField(choices=[('OFF', 'Not offered'), ('PENDING', 'Requested — awaiting approval'), ('ACTIVE', 'Live')], db_index=True, default='OFF', help_text='Blood tests and health packages — the Blood Tests tab.', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='svc_consultations',
            field=models.CharField(choices=[('OFF', 'Not offered'), ('PENDING', 'Requested — awaiting approval'), ('ACTIVE', 'Live')], db_index=True, default='OFF', help_text='Doctors and OPD slots — the Doctors tab.', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='svc_scans',
            field=models.CharField(choices=[('OFF', 'Not offered'), ('PENDING', 'Requested — awaiting approval'), ('ACTIVE', 'Live')], db_index=True, default='OFF', help_text='MRI, CT, X-ray, ultrasound — the Scans tab.', max_length=10),
        ),
    ]
