# Generated by Django 6.0.2 on 2026-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='max_per_slot',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
