# Generated by Django 6.0.2 on 2026-03-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_max_per_slot_doctor_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
