# Generated by Django 5.2.1 on 2026-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_options_alter_doctor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
