# Generated by Django 5.2.1 on 2026-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
