# Generated by Django 5.2.1 on 2026-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ifsc',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='upi_vpa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
