# Generated by Django 5.2.1 on 2026-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_bank_account_number_doctor_ifsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='payment_collection_mode',
            field=models.CharField(choices=[('FULL', 'Doctor Fee + Service Fee'), ('SERVICE_ONLY', 'Service Fee Only')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK', 'Bank Account')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='payout_notes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
