# Generated by Django 5.2.1 on 2026-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_account_holder_name_doctor_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='payout_to_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
