# Generated by Django 6.0.2 on 2026-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_payout_to_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='payment_collection_mode',
            field=models.CharField(choices=[('FULL', 'Doctor Fee + Service Fee'), ('SERVICE_ONLY', 'Service Fee Only')], default='SERVICE_ONLY', max_length=20),
        ),
    ]
