# Generated by Django 5.2.1 on 2026-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_existing_doctors_default_to_service_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='landline',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
