# Generated by Django 5.2.1 on 2026-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctor_landline_alter_doctor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
