# Generated by Django 5.2.1 on 2026-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='booking_cutoff_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
