# Generated by Django 6.0.2 on 2026-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_doctor_booking_cutoff_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='delay_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='running_delay_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
