# Generated by Django 6.0.2 on 2026-06-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_indexes_and_protect'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReschedulePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('signature', models.CharField(blank=True, max_length=300)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='success', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_payments', to='bookings.booking')),
            ],
        ),
    ]
