# Generated by Django 6.0.2 on 2026-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_reschedulepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reschedulepayment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='reschedulepayment',
            name='amount',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reschedulepayment',
            name='signature',
            field=models.TextField(),
        ),
    ]
