# Generated by Django 5.2.1 on 2026-07-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_doctor_payout_status'),
        ('doctors', '0007_doctor_bank_account_number_doctor_ifsc_and_more'),
        ('hospitals', '0008_hospital_commission_rate'),
        ('payments', '0005_backfill_payment_splits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100)),
                ('payout_mode', models.CharField(choices=[('UPI', 'UPI'), ('IMPS', 'IMPS')], max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='QUEUED', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('doctor_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCommissionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_invoices', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('hospital', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='DoctorLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('BOOKING_COMPLETED', 'Booking Completed'), ('HOSPITAL_COMMISSION', 'Hospital Commission'), ('ABSENCE_REFUND', 'Absence Refund')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='bookings.booking')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='doctors.doctor')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payoutbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'payout_batch'], name='idx_ledger_doctor_batch')],
            },
        ),
    ]
