# Generated by Django 5.2.1 on 2026-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_doctor_payout_status'),
        ('payments', '0006_payoutbatch_refund_hospitalcommissioninvoice_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_id', ''), _negated=True), fields=('payment_id',), name='uniq_payment_payment_id_nonblank'),
        ),
    ]
