# Generated by Django 5.2.1 on 2026-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_uniq_payment_payment_id_nonblank'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='offline_doctor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
