# Generated by Django 5.2.1 on 2026-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_offline_doctor_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorledger',
            name='reason',
            field=models.CharField(choices=[('BOOKING_COMPLETED', 'Booking Completed'), ('ABSENCE_REFUND', 'Absence Refund')], max_length=30),
        ),
        migrations.DeleteModel(
            name='HospitalCommissionInvoice',
        ),
    ]
