# Generated by Django 6.0.2 on 2026-08-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_doctorledger_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutbatch',
            name='payout_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('IMPS', 'IMPS'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
