# Generated by Django 5.2.1 on 2026-08-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_scan_alter_booking_doctor_and_more'),
        ('doctors', '0013_doctor_view_count'),
        ('hospitals', '0013_hospital_license_number'),
        ('payments', '0010_alter_payoutbatch_payout_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorledger',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='doctorledger',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='doctors.doctor'),
        ),
        migrations.AddIndex(
            model_name='doctorledger',
            index=models.Index(fields=['center', 'payout_batch'], name='idx_ledger_center_batch'),
        ),
        migrations.AddConstraint(
            model_name='doctorledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('center__isnull', True), ('doctor__isnull', False)), models.Q(('center__isnull', False), ('doctor__isnull', True)), _connector='OR'), name='ledger_exactly_one_payee'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('center__isnull', True), ('doctor__isnull', False)), models.Q(('center__isnull', False), ('doctor__isnull', True)), _connector='OR'), name='payoutbatch_exactly_one_payee'),
        ),
    ]
