# Generated by Django 5.2.1 on 2026-09-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_appointmentpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentpass',
            name='expiry_extended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentpass',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
