# Generated by Django 6.0.2 on 2026-09-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_appointmentpass_expiry_extended_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('payment',), name='unique_payment_refund'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_refund_id', ''), _negated=True), fields=('razorpay_refund_id',), name='unique_razorpay_refund_id'),
        ),
    ]
