# Generated by Django 5.2.1 on 2026-08-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_whatsapp_opt_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='idx_ratecounter_expires')],
            },
        ),
    ]
